In [1]:
import yfinance as yf

# Fetch Tesla stock data
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="1y")  
tesla_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-08-03 00:00:00-04:00,252.039993,260.489990,252.000000,259.320007,97569100,0.0,0.0
2023-08-04 00:00:00-04:00,260.970001,264.769989,253.110001,253.860001,99242600,0.0,0.0
2023-08-07 00:00:00-04:00,251.449997,253.649994,242.759995,251.449997,111097900,0.0,0.0
2023-08-08 00:00:00-04:00,247.449997,250.919998,245.009995,249.699997,96642200,0.0,0.0
2023-08-09 00:00:00-04:00,250.869995,251.100006,241.899994,242.190002,101596300,0.0,0.0

## Tesla Stock Data

The code above fetches Tesla's stock data for the past year using the `yfinance` library. The output shows a preview of the data, including open, high, low, close prices, and volume.

In [2]:
import requests
from bs4 import BeautifulSoup

url = "https://finance.yahoo.com/quote/TSLA/financials?p=TSLA"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')


try:
   
    revenue_elements = soup.find_all("div", class_="D(ib) Mend(20px)")
    
    for element in revenue_elements:
      
        text = element.get_text(strip=True)
        if "Revenue" in text:
            revenue = text
            break
    else:
        revenue = "Revenue data not found"

except Exception as e:
    revenue = f"An error occurred: {e}"

print("Tesla Revenue Data:", revenue)

Tesla Revenue Data: Revenue data not found

Question 3: Extracting GameStop Stock Data

In [3]:
# Fetch GameStop stock data
gamestop = yf.Ticker("GME")
gamestop_data = gamestop.history(period="1y")  # Adjust the period as needed
gamestop_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-08-03 00:00:00-04:00,20.879999,21.180000,20.740000,20.93,1318700,0.0,0.0
2023-08-04 00:00:00-04:00,20.950001,21.889999,20.889999,20.98,2400500,0.0,0.0
2023-08-07 00:00:00-04:00,20.900000,21.240000,20.480000,21.07,1441300,0.0,0.0
2023-08-08 00:00:00-04:00,20.700001,20.900000,20.280001,20.74,1431300,0.0,0.0
2023-08-09 00:00:00-04:00,20.850000,20.850000,19.820000,19.93,2929600,0.0,0.0

## GameStop Stock Data

The code above fetches GameStop's stock data for the past year using the `yfinance` library. The output shows a preview of the data, including open, high, low, close prices, and volume.

In [4]:
import dash
from dash import dcc, html
import plotly.graph_objs as go

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Tesla Stock and Revenue Dashboard"),
    dcc.Graph(
        id='tesla-stock-graph',
        figure={
            'data': [
                go.Scatter(
                    x=tesla_data.index,
                    y=tesla_data['Close'],
                    mode='lines',
                    name='Tesla Stock Price'
                )
            ],
            'layout': {
                'title': 'Tesla Stock Price'
            }
        }
    ),
])

if __name__ == '__main__':
    app.run_server(debug=True)

ModuleNotFoundError: No module named 'dash'

In [5]:
import dash
from dash import dcc, html
import plotly.graph_objs as go

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Tesla Stock and Revenue Dashboard"),
    dcc.Graph(
        id='tesla-stock-graph',
        figure={
            'data': [
                go.Scatter(
                    x=tesla_data.index,
                    y=tesla_data['Close'],
                    mode='lines',
                    name='Tesla Stock Price'
                )
            ],
            'layout': {
                'title': 'Tesla Stock Price'
            }
        }
    ),
])

if __name__ == '__main__':
    app.run_server(debug=True)

## Tesla Stock and Revenue Dashboard

The dashboard visualizes Tesla's stock price and revenue data. Please note that the full functionality of the dashboard may require running the app separately.

In [8]:
import dash
from dash import dcc, html
import plotly.graph_objs as go
import yfinance as yf

gamestop = yf.Ticker("GME")
gamestop_data = gamestop.history(period="1y")
app = dash.Dash(__name__)
app.layout = html.Div([
    html.H1("GameStop Stock Price Dashboard"),
    
    dcc.Graph(
        id='gamestop-stock-graph',
        figure={
            'data': [
                go.Scatter(
                    x=gamestop_data.index,
                    y=gamestop_data['Close'],
                    mode='lines',
                    name='GameStop Stock Price'
                )
            ],
            'layout': {
                'title': 'GameStop Stock Price',
                'xaxis': {'title': 'Date'},
                'yaxis': {'title': 'Price (USD)'}
            }
        }
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

## GameStop Stock and Revenue Dashboard

The dashboard visualizes GameStop's stock price and revenue data. Please note that the full functionality of the dashboard may require running the app separately.